# Generated by Django 2.2.1 on 2019-05-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(default='uploads/default-post-img.jpg', upload_to='uploads/%Y/%m/%d'),
        ),
    ]
